apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: cdsap/bagan-init
            args:
            - /bin/sh
            - -c
            - echo 1
          restartPolicy: OnFailure
