package com.cdsap.bagan.generator

data class Panel(
    val content: String? = null,
    val id: Int,
    val type: String? = "null",
    val mode: String? = "null",
    val title: String,
    val gridPos: Gridpos,
    val aliasColors: Array<Any> = emptyArray(),
    var bars: Boolean = false,
    val dashLength: Int = 10,
    val dashes: Boolean = false,
    val dataSource: String = "influxdb",
    val fill: Int = 2,
    val lines: Boolean = true,
    val lineWidth: Int = 1,
    val nullPointMode: String = "connected",
    val percentage: Boolean = false,
    val pointradius: Int = 2,
    val points: Boolean = true,
    val renderer: String = "flot",
    val spaceLength: Int = 10,
    val steppedLine: Boolean = false,
    val stack: Boolean = false,
    val legend: Legend = Legend(),
    val seriesOverrides: Array<String> = emptyArray(),
    val thresholds: Array<String>? = null,
    val timeRegions: Array<String> = emptyArray(),
    val tooltip: Tooltip = Tooltip(),
    val xaxis: Xaxis = Xaxis(),
    val yaxes: Array<Yaxes> = arrayOf(
        Yaxes(format = "ms"),
        Yaxes()
    ),
    val yaxis: Yaxis = Yaxis(),
    val targets: Array<Target>? = null,
    var timeFrom: Any? = null,
    var timeShift: Any? = null,
    val options: Options = Options(),
    val links: Array<String>? = emptyArray(),
    val cacheTimeout: Boolean = false,
    val colorBackground: Boolean = false,
    val colorValue: Boolean = false,
    val format: String = "none",
    val interval: String? = null,
    val mappingType: Int = 1,
    val maxDataPoints: Int = 100,
    val nullText: String? = null,
    val postfix: String = "",
    val postfixFontSize: String = "50%",
    val prefix: String = "",
    val prefixFontSize: String = "50%",
    val tableColumn: String = "",
    val valueFontSize: String = "50%",
    val valueName: String? = null,
    val colors: Array<String> = arrayOf(
        "#299c46", "rgba(237, 129, 40, 0.89)", "#d44a3a"
    ),
    val gauge: Gauge = Gauge(),
    val mappingTypes: Array<MappingType> = arrayOf(
        MappingType(name = "value to text", value = 1),
        MappingType(name = "range to text", value = 2)
    ),
    val rangeMaps: Array<RangeMap> = arrayOf(RangeMap()),
    val sparkLine: SparkLine = SparkLine(),
    val pageSize: Any? = null,
    val scroll: Boolean = true,
    val showHeader: Boolean = true,
    val sort: Sort = Sort(2, false),
    val transform: String = "table",
    val style: Array<Any> = arrayOf(Style(), Style2()),
    val styles: Array<Any> = arrayOf(
        Style(), Style2()
    )
)