apiVersion: v1
kind: ConfigMap
metadata:
  name: all-nodes-dashboard
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "dashboards/dashboard.json").AsConfig | indent 2 }}
